/* =====================================================================
   ALPHA ARTIFICIAL — univers.js  (GENERAT AUTOMÀTICAMENT)
   ---------------------------------------------------------------------
   NO EDITIS AQUEST FITXER A MÀ: es genera des de config.py amb
       python generar_univers_web.py
   ===================================================================== */
(function () {
  "use strict";

  window.ALPHA_ACCIONS = {
    "AAPL": {
      "nom": "Apple",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "L'iPhone, el Mac i l'App Store. Una de les empreses més valuoses del món.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "MSFT": {
      "nom": "Microsoft",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Windows, Office, la núvol Azure i una aposta enorme per la IA.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "NVDA": {
      "nom": "Nvidia",
      "cat": "Semiconductors",
      "art": "ai",
      "risc": 5,
      "desc": "Els xips que fan funcionar la intel·ligència artificial. El gran guanyador del boom de la IA.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "GOOGL": {
      "nom": "Alphabet (Google)",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "El cercador de Google, YouTube, Android i el model Gemini.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "AMZN": {
      "nom": "Amazon",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "La botiga en línia més gran del món i AWS, líder mundial en servidors al núvol.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "META": {
      "nom": "Meta (Facebook)",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Facebook, Instagram i WhatsApp: la companyia de xarxes socials més gran.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "TSLA": {
      "nom": "Tesla",
      "cat": "Automoció",
      "art": "auto",
      "risc": 4,
      "desc": "Cotxes elèctrics, bateries i conducció autònoma. Molt volàtil.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "AMD": {
      "nom": "AMD",
      "cat": "Semiconductors",
      "art": "ai",
      "risc": 5,
      "desc": "Competidor directe de Nvidia i Intel en xips i processadors.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "INTC": {
      "nom": "Intel",
      "cat": "Semiconductors",
      "art": "ai",
      "risc": 5,
      "desc": "El fabricant de xips clàssic dels EUA, en plena reinvenció.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "AVGO": {
      "nom": "Broadcom",
      "cat": "Semiconductors",
      "art": "ai",
      "risc": 5,
      "desc": "Xips per a mòbils, xarxes i centres de dades. Gegant discret del sector.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "QCOM": {
      "nom": "Qualcomm",
      "cat": "Semiconductors",
      "art": "ai",
      "risc": 5,
      "desc": "Els processadors i mòdems que porten la majoria de mòbils Android.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "CRM": {
      "nom": "Salesforce",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Salesforce: el programari amb què les empreses gestionen els seus clients.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "ORCL": {
      "nom": "Oracle",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Bases de dades corporatives i infraestructura al núvol.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "ADBE": {
      "nom": "Adobe",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Photoshop, Illustrator i el PDF. L'eina de tots els dissenyadors.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "IBM": {
      "nom": "IBM",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "El veterà de la informàtica: serveis corporatius i computació quàntica.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "CSCO": {
      "nom": "Cisco",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Els encaminadors i xarxes per on passa bona part d'internet.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "NFLX": {
      "nom": "Netflix",
      "cat": "Mitjans",
      "art": "media",
      "risc": 4,
      "desc": "Netflix: streaming i producció pròpia de sèries i pel·lícules.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "PLTR": {
      "nom": "Palantir",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Anàlisi massiva de dades per a governs i grans empreses.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "JNJ": {
      "nom": "Johnson & Johnson",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Farmacèutica gegant i productes de salut de consum.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "LLY": {
      "nom": "Eli Lilly",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Els fàrmacs contra l'obesitat i la diabetis que han disparat la companyia.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "PFE": {
      "nom": "Pfizer",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "La farmacèutica de la vacuna de la covid.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "MRK": {
      "nom": "Merck",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Farmacèutica centrada en oncologia i vacunes.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "ABBV": {
      "nom": "AbbVie",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Immunologia i estètica mèdica (Botox).",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "UNH": {
      "nom": "UnitedHealth",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "L'asseguradora de salut més gran dels EUA.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "AMGN": {
      "nom": "Amgen",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Biotecnològica veterana especialitzada en teràpies avançades.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "MRNA": {
      "nom": "Moderna",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "L'ARN missatger: vacunes de nova generació. Aposta d'alt risc.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "JPM": {
      "nom": "JPMorgan Chase",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "El banc més gran dels Estats Units.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "BAC": {
      "nom": "Bank of America",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Bank of America: banca minorista i d'inversió.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "GS": {
      "nom": "Goldman Sachs",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Goldman Sachs, la banca d'inversió per excel·lència.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "V": {
      "nom": "Visa",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Visa: cobra una comissió de gairebé cada pagament amb targeta del món.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "MA": {
      "nom": "Mastercard",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Mastercard, l'altre gran peatge dels pagaments globals.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "AXP": {
      "nom": "American Express",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "American Express: targetes premium i clients d'alt poder adquisitiu.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "BRK-B": {
      "nom": "Berkshire Hathaway",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "El hòlding de Warren Buffett: assegurances, ferrocarrils i accions.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "PYPL": {
      "nom": "PayPal",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "PayPal: pagaments en línia arreu del món.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "KO": {
      "nom": "Coca-Cola",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Coca-Cola. La marca de begudes més reconeguda del planeta.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "PEP": {
      "nom": "PepsiCo",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Pepsi, Lay's, Doritos i Gatorade.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "MCD": {
      "nom": "McDonald's",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "McDonald's: menjar ràpid i, sobretot, un negoci immobiliari enorme.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "NKE": {
      "nom": "Nike",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Nike: roba i calçat esportiu.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "SBUX": {
      "nom": "Starbucks",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Starbucks: la cadena de cafeteries més gran del món.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "WMT": {
      "nom": "Walmart",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Walmart, el supermercat més gran dels EUA.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "COST": {
      "nom": "Costco",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Costco: venda a l'engròs amb quota de soci.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "PG": {
      "nom": "Procter & Gamble",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Ariel, Dodot, Gillette... productes que es compren passi el que passi.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "HD": {
      "nom": "Home Depot",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Home Depot: bricolatge i reformes de la llar.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "DIS": {
      "nom": "Walt Disney",
      "cat": "Mitjans",
      "art": "media",
      "risc": 4,
      "desc": "Disney: pel·lícules, parcs temàtics i Disney+.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "XOM": {
      "nom": "ExxonMobil",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "ExxonMobil, la petroliera més gran dels EUA.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "CVX": {
      "nom": "Chevron",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "Chevron: petroli i gas arreu del món.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "BA": {
      "nom": "Boeing",
      "cat": "Indústria",
      "art": "industry",
      "risc": 3,
      "desc": "Boeing: avions comercials i defensa.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "CAT": {
      "nom": "Caterpillar",
      "cat": "Indústria",
      "art": "industry",
      "risc": 3,
      "desc": "Caterpillar: maquinària de construcció i mineria.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "GE": {
      "nom": "General Electric",
      "cat": "Indústria",
      "art": "industry",
      "risc": 3,
      "desc": "General Electric: turbines d'avió i energia.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "LMT": {
      "nom": "Lockheed Martin",
      "cat": "Defensa",
      "art": "defense",
      "risc": 3,
      "desc": "Lockheed Martin: caces F-35 i sistemes de defensa.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "RTX": {
      "nom": "RTX (Raytheon)",
      "cat": "Defensa",
      "art": "defense",
      "risc": 3,
      "desc": "Motors d'avió i míssils. Indústria de defensa pesant.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "DE": {
      "nom": "John Deere",
      "cat": "Indústria",
      "art": "industry",
      "risc": 3,
      "desc": "John Deere: la maquinària agrícola verda de tota la vida.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "UPS": {
      "nom": "UPS",
      "cat": "Logística",
      "art": "airline",
      "risc": 3,
      "desc": "Paqueteria i logística mundial.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "T": {
      "nom": "AT&T",
      "cat": "Telecomunicacions",
      "art": "media",
      "risc": 2,
      "desc": "AT&T: telefonia i internet als Estats Units.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "VZ": {
      "nom": "Verizon",
      "cat": "Telecomunicacions",
      "art": "media",
      "risc": 2,
      "desc": "Verizon, l'altra gran teleco americana.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "UBER": {
      "nom": "Uber",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Uber: transport de persones i repartiment de menjar.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "ABNB": {
      "nom": "Airbnb",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Airbnb: allotjaments turístics d'particulars.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "COIN": {
      "nom": "Coinbase",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Coinbase: la borsa de criptomonedes cotitzada. Molt volàtil.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "F": {
      "nom": "Ford",
      "cat": "Automoció",
      "art": "auto",
      "risc": 4,
      "desc": "Ford: cotxes, pickups i transició a l'elèctric.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "GM": {
      "nom": "General Motors",
      "cat": "Automoció",
      "art": "auto",
      "risc": 4,
      "desc": "General Motors: Chevrolet, Cadillac i vehicles elèctrics.",
      "tipus": "accio",
      "pais": "EUA",
      "bandera": "🇺🇸",
      "moneda": "USD"
    },
    "ITX.MC": {
      "nom": "Inditex (Zara)",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Zara, Bershka i Massimo Dutti. La joia de la corona espanyola.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "SAN.MC": {
      "nom": "Banco Santander",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Banco Santander: el banc espanyol més internacional.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "BBVA.MC": {
      "nom": "BBVA",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "BBVA: banca a Espanya, Mèxic i Turquia.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "IBE.MC": {
      "nom": "Iberdrola",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "Iberdrola: electricitat i lideratge mundial en renovables.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "TEF.MC": {
      "nom": "Telefónica",
      "cat": "Telecomunicacions",
      "art": "media",
      "risc": 2,
      "desc": "Telefónica (Movistar): telefonia a Espanya i Llatinoamèrica.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "REP.MC": {
      "nom": "Repsol",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "Repsol: refineries, benzineres i energia.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "GRF.MC": {
      "nom": "Grifols",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Empresa CATALANA líder mundial en medicaments derivats del plasma.",
      "tipus": "accio",
      "pais": "Catalunya",
      "bandera": "🏴",
      "moneda": "EUR"
    },
    "CLNX.MC": {
      "nom": "Cellnex",
      "cat": "Telecomunicacions",
      "art": "media",
      "risc": 2,
      "desc": "Empresa CATALANA propietària de torres de telecomunicacions per tota Europa.",
      "tipus": "accio",
      "pais": "Catalunya",
      "bandera": "🏴",
      "moneda": "EUR"
    },
    "FER.MC": {
      "nom": "Ferrovial",
      "cat": "Indústria",
      "art": "industry",
      "risc": 3,
      "desc": "Ferrovial: autopistes i aeroports arreu del món.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "AENA.MC": {
      "nom": "Aena (aeroports)",
      "cat": "Indústria",
      "art": "industry",
      "risc": 3,
      "desc": "Aena: gestiona tots els aeroports espanyols, inclòs el Prat.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "ELE.MC": {
      "nom": "Endesa",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "Endesa: una de les grans elèctriques espanyoles.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "AMS.MC": {
      "nom": "Amadeus",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Amadeus: la tecnologia darrere de la majoria de reserves de vols.",
      "tipus": "accio",
      "pais": "Espanya",
      "bandera": "🇪🇸",
      "moneda": "EUR"
    },
    "MC.PA": {
      "nom": "LVMH (Louis Vuitton)",
      "cat": "Luxe",
      "art": "luxe",
      "risc": 3,
      "desc": "LVMH: Louis Vuitton, Dior i Moët. El gegant del luxe.",
      "tipus": "accio",
      "pais": "França",
      "bandera": "🇫🇷",
      "moneda": "EUR"
    },
    "RMS.PA": {
      "nom": "Hermès",
      "cat": "Luxe",
      "art": "luxe",
      "risc": 3,
      "desc": "Hermès: els bosses Birkin i el luxe més exclusiu.",
      "tipus": "accio",
      "pais": "França",
      "bandera": "🇫🇷",
      "moneda": "EUR"
    },
    "OR.PA": {
      "nom": "L'Oréal",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "L'Oréal: cosmètica número u del món.",
      "tipus": "accio",
      "pais": "França",
      "bandera": "🇫🇷",
      "moneda": "EUR"
    },
    "AIR.PA": {
      "nom": "Airbus",
      "cat": "Indústria",
      "art": "industry",
      "risc": 3,
      "desc": "Airbus: el rival europeu de Boeing.",
      "tipus": "accio",
      "pais": "França",
      "bandera": "🇫🇷",
      "moneda": "EUR"
    },
    "TTE.PA": {
      "nom": "TotalEnergies",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "TotalEnergies: petroli, gas i renovables.",
      "tipus": "accio",
      "pais": "França",
      "bandera": "🇫🇷",
      "moneda": "EUR"
    },
    "SAN.PA": {
      "nom": "Sanofi",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Sanofi: farmacèutica francesa i vacunes.",
      "tipus": "accio",
      "pais": "França",
      "bandera": "🇫🇷",
      "moneda": "EUR"
    },
    "BNP.PA": {
      "nom": "BNP Paribas",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "BNP Paribas: el banc més gran de la zona euro.",
      "tipus": "accio",
      "pais": "França",
      "bandera": "🇫🇷",
      "moneda": "EUR"
    },
    "CAP.PA": {
      "nom": "Capgemini",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Capgemini: consultoria i serveis tecnològics.",
      "tipus": "accio",
      "pais": "França",
      "bandera": "🇫🇷",
      "moneda": "EUR"
    },
    "SAP.DE": {
      "nom": "SAP",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "SAP: el programari de gestió de les grans empreses europees.",
      "tipus": "accio",
      "pais": "Alemanya",
      "bandera": "🇩🇪",
      "moneda": "EUR"
    },
    "SIE.DE": {
      "nom": "Siemens",
      "cat": "Indústria",
      "art": "industry",
      "risc": 3,
      "desc": "Siemens: automatització industrial, trens i tecnologia mèdica.",
      "tipus": "accio",
      "pais": "Alemanya",
      "bandera": "🇩🇪",
      "moneda": "EUR"
    },
    "ALV.DE": {
      "nom": "Allianz",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Allianz: una de les asseguradores més grans del món.",
      "tipus": "accio",
      "pais": "Alemanya",
      "bandera": "🇩🇪",
      "moneda": "EUR"
    },
    "BMW.DE": {
      "nom": "BMW",
      "cat": "Automoció",
      "art": "auto",
      "risc": 4,
      "desc": "BMW: cotxes premium i Mini.",
      "tipus": "accio",
      "pais": "Alemanya",
      "bandera": "🇩🇪",
      "moneda": "EUR"
    },
    "MBG.DE": {
      "nom": "Mercedes-Benz",
      "cat": "Automoció",
      "art": "auto",
      "risc": 4,
      "desc": "Mercedes-Benz: automoció de gamma alta.",
      "tipus": "accio",
      "pais": "Alemanya",
      "bandera": "🇩🇪",
      "moneda": "EUR"
    },
    "ADS.DE": {
      "nom": "Adidas",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Adidas: el rival europeu de Nike.",
      "tipus": "accio",
      "pais": "Alemanya",
      "bandera": "🇩🇪",
      "moneda": "EUR"
    },
    "DTE.DE": {
      "nom": "Deutsche Telekom",
      "cat": "Telecomunicacions",
      "art": "media",
      "risc": 2,
      "desc": "Deutsche Telekom, propietària de T-Mobile.",
      "tipus": "accio",
      "pais": "Alemanya",
      "bandera": "🇩🇪",
      "moneda": "EUR"
    },
    "BAS.DE": {
      "nom": "BASF",
      "cat": "Química",
      "art": "industry",
      "risc": 3,
      "desc": "BASF: la química més gran del món.",
      "tipus": "accio",
      "pais": "Alemanya",
      "bandera": "🇩🇪",
      "moneda": "EUR"
    },
    "ASML.AS": {
      "nom": "ASML",
      "cat": "Semiconductors",
      "art": "ai",
      "risc": 5,
      "desc": "Fabrica les úniques màquines del món capaces de gravar els xips més avançats. Peça clau del planeta.",
      "tipus": "accio",
      "pais": "Països Baixos",
      "bandera": "🇳🇱",
      "moneda": "EUR"
    },
    "ADYEN.AS": {
      "nom": "Adyen",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Adyen: la passarel·la de pagaments d'Uber, Spotify i eBay.",
      "tipus": "accio",
      "pais": "Països Baixos",
      "bandera": "🇳🇱",
      "moneda": "EUR"
    },
    "PHIA.AS": {
      "nom": "Philips",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Philips: equipament mèdic i salut personal.",
      "tipus": "accio",
      "pais": "Països Baixos",
      "bandera": "🇳🇱",
      "moneda": "EUR"
    },
    "ABI.BR": {
      "nom": "AB InBev",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "AB InBev: Estrella, Corona, Budweiser... la cervesera més gran.",
      "tipus": "accio",
      "pais": "Bèlgica",
      "bandera": "🇧🇪",
      "moneda": "EUR"
    },
    "RACE": {
      "nom": "Ferrari",
      "cat": "Automoció",
      "art": "auto",
      "risc": 4,
      "desc": "Ferrari: cotxes esportius de luxe amb marges altíssims.",
      "tipus": "accio",
      "pais": "Itàlia",
      "bandera": "🇮🇹",
      "moneda": "USD"
    },
    "ENI.MI": {
      "nom": "Eni",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "Eni: la petroliera italiana.",
      "tipus": "accio",
      "pais": "Itàlia",
      "bandera": "🇮🇹",
      "moneda": "EUR"
    },
    "ISP.MI": {
      "nom": "Intesa Sanpaolo",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "Intesa Sanpaolo: el gran banc italià.",
      "tipus": "accio",
      "pais": "Itàlia",
      "bandera": "🇮🇹",
      "moneda": "EUR"
    },
    "STLAM.MI": {
      "nom": "Stellantis",
      "cat": "Automoció",
      "art": "auto",
      "risc": 4,
      "desc": "Stellantis: Peugeot, Fiat, Citroën, Jeep i Opel.",
      "tipus": "accio",
      "pais": "Itàlia",
      "bandera": "🇮🇹",
      "moneda": "EUR"
    },
    "NESN.SW": {
      "nom": "Nestlé",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Nestlé: Nespresso, KitKat i Purina. Consum bàsic mundial.",
      "tipus": "accio",
      "pais": "Suïssa",
      "bandera": "🇨🇭",
      "moneda": "CHF"
    },
    "NOVN.SW": {
      "nom": "Novartis",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "Novartis: farmacèutica suïssa de primer nivell.",
      "tipus": "accio",
      "pais": "Suïssa",
      "bandera": "🇨🇭",
      "moneda": "CHF"
    },
    "UBSG.SW": {
      "nom": "UBS",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "UBS: banca privada i gestió de grans fortunes.",
      "tipus": "accio",
      "pais": "Suïssa",
      "bandera": "🇨🇭",
      "moneda": "CHF"
    },
    "SHEL.L": {
      "nom": "Shell",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "Shell: una de les petrolieres més grans del món.",
      "tipus": "accio",
      "pais": "Regne Unit",
      "bandera": "🇬🇧",
      "moneda": "GBP"
    },
    "BP.L": {
      "nom": "BP",
      "cat": "Energia",
      "art": "energy",
      "risc": 4,
      "desc": "BP: petroli, gas i transició energètica.",
      "tipus": "accio",
      "pais": "Regne Unit",
      "bandera": "🇬🇧",
      "moneda": "GBP"
    },
    "AZN.L": {
      "nom": "AstraZeneca",
      "cat": "Salut",
      "art": "health",
      "risc": 3,
      "desc": "AstraZeneca: oncologia i la vacuna de la covid.",
      "tipus": "accio",
      "pais": "Regne Unit",
      "bandera": "🇬🇧",
      "moneda": "GBP"
    },
    "HSBA.L": {
      "nom": "HSBC",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "HSBC: banca global amb molt de pes a Àsia.",
      "tipus": "accio",
      "pais": "Regne Unit",
      "bandera": "🇬🇧",
      "moneda": "GBP"
    },
    "ULVR.L": {
      "nom": "Unilever",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Unilever: Dove, Magnum, Hellmann's i Frigo.",
      "tipus": "accio",
      "pais": "Regne Unit",
      "bandera": "🇬🇧",
      "moneda": "GBP"
    },
    "RIO.L": {
      "nom": "Rio Tinto",
      "cat": "Mineria",
      "art": "copper",
      "risc": 4,
      "desc": "Rio Tinto: mineria de ferro, coure i liti.",
      "tipus": "accio",
      "pais": "Regne Unit",
      "bandera": "🇬🇧",
      "moneda": "GBP"
    },
    "TSM": {
      "nom": "TSMC (xips Taiwan)",
      "cat": "Semiconductors",
      "art": "ai",
      "risc": 5,
      "desc": "Fabrica físicament els xips de Nvidia i Apple. L'empresa més estratègica d'Àsia.",
      "tipus": "accio",
      "pais": "Taiwan",
      "bandera": "🇹🇼",
      "moneda": "USD"
    },
    "7203.T": {
      "nom": "Toyota",
      "cat": "Automoció",
      "art": "auto",
      "risc": 4,
      "desc": "Toyota: el fabricant de cotxes més gran del món.",
      "tipus": "accio",
      "pais": "Japó",
      "bandera": "🇯🇵",
      "moneda": "JPY"
    },
    "6758.T": {
      "nom": "Sony",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Sony: PlayStation, càmeres, música i cinema.",
      "tipus": "accio",
      "pais": "Japó",
      "bandera": "🇯🇵",
      "moneda": "JPY"
    },
    "005930.KS": {
      "nom": "Samsung Electronics",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Samsung: mòbils, televisors i memòries. Gegant coreà.",
      "tipus": "accio",
      "pais": "Corea del Sud",
      "bandera": "🇰🇷",
      "moneda": "KRW"
    },
    "BABA": {
      "nom": "Alibaba",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "Alibaba: el comerç electrònic i el núvol de la Xina.",
      "tipus": "accio",
      "pais": "Xina",
      "bandera": "🇨🇳",
      "moneda": "USD"
    },
    "PDD": {
      "nom": "PDD (Temu)",
      "cat": "Consum",
      "art": "consumer",
      "risc": 2,
      "desc": "PDD, propietària de Temu: comerç ultrabarat en expansió mundial.",
      "tipus": "accio",
      "pais": "Xina",
      "bandera": "🇨🇳",
      "moneda": "USD"
    },
    "NTES": {
      "nom": "NetEase",
      "cat": "Mitjans",
      "art": "media",
      "risc": 4,
      "desc": "NetEase: videojocs i música en línia a la Xina.",
      "tipus": "accio",
      "pais": "Xina",
      "bandera": "🇨🇳",
      "moneda": "USD"
    },
    "INFY": {
      "nom": "Infosys",
      "cat": "Tecnologia",
      "art": "tech",
      "risc": 4,
      "desc": "Infosys: serveis informàtics des de l'Índia per a mig món.",
      "tipus": "accio",
      "pais": "Índia",
      "bandera": "🇮🇳",
      "moneda": "USD"
    },
    "HDB": {
      "nom": "HDFC Bank",
      "cat": "Finances",
      "art": "finance",
      "risc": 4,
      "desc": "HDFC Bank: el banc privat més gran de l'Índia.",
      "tipus": "accio",
      "pais": "Índia",
      "bandera": "🇮🇳",
      "moneda": "USD"
    }
  };

  window.ALPHA_SECTORS = ["Automoció", "Consum", "Defensa", "Energia", "Finances", "Indústria", "Logística", "Luxe", "Mineria", "Mitjans", "Química", "Salut", "Semiconductors", "Tecnologia", "Telecomunicacions"];
  window.ALPHA_PAISOS = ["Alemanya", "Bèlgica", "Catalunya", "Corea del Sud", "EUA", "Espanya", "França", "Itàlia", "Japó", "Països Baixos", "Regne Unit", "Suïssa", "Taiwan", "Xina", "Índia"];
})();
